[package]
name = "vara_perp_dex_app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs = "0.9.2"
sp-core = { version = "38.1.0", default-features = false }
primitive-types = { version = "0.14.0", default-features = false }